displayName=Lag Alarm
author=trippy22
description=Warns about delayed game updates, unstable game connections and high latency with visual and spoken alerts.
tags=lag,latency,connection,alarm,hardcore,ironman,hcim,ping
plugins=com.lagalarm.LagAlarmPlugin
build=standard
version=0.2.0
